formulario/urls.py
from . import views
from django.urls import path

app_name = 'formulario'

urlpatterns = [
	  path('', views.enviar_mensagem, name = 'enviar_mensagem'),
	  path('projetos-python/', views.projetos_python, name = 'projetos_python'),
	  path('projetos-designer-grafico/', views.projetos_designer, name = 'projetos_designer'),
	  path('projetos-html-css-javascript/', views.projetos_web, name = 'projetos_web'),
      path('projetos-django.html/', views.projetos_django, name = 'projetos_django'),

	]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('formulario.urls', namespace = 'enviar_mensagem')),
    ]

formulario/models.py
from django.db import models

class Contato(models.Model):
    nome = models.CharField(max_length=100)
    email = models.EmailField(max_length=100)
    assunto = models.CharField(max_length=100)
    mensagem = models.TextField()

    def __str__(self):
        return self.nome
# Create your models here.

formulario/views.py
from django.shortcuts import render
from django.core.mail import EmailMessage
from django.conf import settings
from django.http import HttpResponseRedirect

def enviar_mensagem(request):
    if request.method == 'POST':
        nome = request.POST['nome']
        email = request.POST['email']
        assunto = request.POST['assunto']
        mensagem = request.POST['mensagem']

        # Configuração do e-mail
        remetente = email  # Usando o e-mail do remetente como o remetente do e-mail
        destinatario_host = 'augustodomingosvasco@gmail.com' 

        email_remessa_host = EmailMessage(
            assunto,
            f"Mensagem de {nome}\n\n{mensagem}",
            remetente,
            [destinatario_host],
            reply_to=[remetente]
        )

        # Envio do e-mail para mim
        email_remessa_host.send()

        return render(request, 'mensagem_enviada.html')

    return render(request, 'index.html')

    
# Requisição para as paginas dentro da pasta Template
def projetos_python(request):
  return render(request, 'projetos-python.html')
  
def projetos_designer(request):
  return render(request, 'projetos-designer-grafico.html')
  
def projetos_web(request):
  return render(request, 'projetos-html-css-javascript.html')

def projetos_django(request):
  return render(request, 'projetos-django.html')
  

formulario/templates/mensagem_enviada.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mensagem Enviada</title>
    <link rel="icon" href="{% static 'images/icon/GD_ICON_TELA.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
    <script src="{% static 'js/all.min.6.1.1.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/typed.min.js' %}"></script>
</head>
<body class="mens_corp">
   <div class="container">
    <h1>Mensagem Enviada com Sucesso!</h1>
    <p>Obrigado por entrar em contato. Sua mensagem foi enviada com sucesso.</p>
    <p>Entrarei em contato com você em breve para responder às suas perguntas ou solicitações.</p>
    <p>Enquanto isso, sinta-se à vontade para explorar mais sobre o meu trabalho visitando a <a href="https://aghastygd.pythonanywhere.com/">página inicial</a>.</p>
  </div>
  </body>
</html>

formulario/templates/projetos-designer-grafico.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projetos Designer Gráfico | Augusto Domingos</title>
    <link rel="icon" href="{% static 'images/icon/GD_ICON_TELA.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
    <script src="{% static 'js/all.min.6.1.1.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/typed.min.js' %}"></script>
   
</head>
<body>
    <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="index.html">Proje<span>tos</span></a> </div>
            <ul class="menu">
                <li><a href="index.html#home">Início</a></li>
                <li><a href="index.html#about">Sobre</a></li>
                <li><a href="index.html#services">Projetos</a></li>
                <li><a href="index.html#skills">Skills</a></li>
                <li><a href="index.html#contact">Contacto</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>

    <!-- seção da página inicial -->
    <section class="about" id="about">
        <div class="max-width">
            <h2 class="title">Edição de Vídeos</h2>
                
            <div class="about-content">
                <div class="column left">
                    <img src="{% static 'images/projetos/projetovid_001.jpg' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p class="p1">Edição de vídeo sempre foi um hobby meu, e agora eu transformei isso em uma das minhas habilidades. Tenho experiência de mais de 3 anos nessa área, trabalhando com programas como Wondershare Filmora, Camtasia Studio, Inshot e Sony Vegas. Posso criar efeitos incríveis, incluindo remoção de fundos (Chroma Key), sincronização do áudio com o vídeo, transições, legendas e muitas outras coisas. Confira alguns dos meus trabalhos já concluídos, como AMVs, EDITS, Slideshows, Nuggets, Lyrics Videos e Chroma Key, a maioria disponível no meu canal do YouTube e outros adicionais estão na pasta do Drive. Clique nos links abaixo para conferir!</p>
                    <h2 class="text2">Demonstração dos Vídeos</h2>
                    <p> <a class="a1" href="#" >Abrir o Drive</a> <a class="a1" href="https://www.youtube.com/channel/UCutT1cn1HmPOCk2y2LVM7RA/videos" target="_blank" > Abrir o Canal do Youtube</a> </p> 
                </div>                   
                </div>
            </div>
        </div>
        
    </section>
</footer>
<footer>
<span>Criado por <a href="https://augustodomingos.netlify.app/">Augusto Domingos</a> | <span class="far fa-copyright"></span> 2023 Todos os direitos reservados.</span>
</footer>
    
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

formulario/templates/projetos-django.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projetos com Django | Augusto Domingos</title>
    <link rel="icon" href="{% static 'images/icon/GD_ICON_TELA.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
    <script src="{% static 'js/all.min.6.1.1.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/typed.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
   
</head>
<body>
    <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="{% url 'formulario:enviar_mensagem' %}">Proje<span>tos</span></a> </div>
            <ul class="menu">
                <li><a href={% url 'formulario:enviar_mensagem' %}>Início</a></li>
                <li><a href="index.html#about">Sobre</a></li>
                <li><a href="index.html#services">Projetos</a></li>
                <li><a href="index.html#skills">Skills</a></li>
                <li><a href="index.html#contact">Contacto</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>

    <!-- seção da página inicial -->
    <section class="about" id="about">
        <div class="max-width">
            <h2 class="title">Sistema de Login Completo</h2>
                
            <div class="about-content">
                <div class="slideshow">
                    <img src="{% static 'images/projetos/login_system_01.png' %}" alt="">
                    <img src="{% static 'images/projetos/login_system_02.png' %}" alt="">
                    <img src="{% static 'images/projetos/login_system_03.png' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p class="p1">Um Sistema de Login que permite que os usuários se registrem, façam login e realizem a autenticação em um ambiente web seguro.
                        Utilizei o framework Django e algumas bibliotecas do Python como o SendGrid para fornecer recursos completos de autenticação e gerenciamento de usuários.
                    </p>
        
                    <h2 class="text2">Demonstração do Sistema</h2>
                    <p class="p1"><a class='a1' href="https://github.com/AghastyGD/sistema_de_login-Django" target = "_blank"> Abrir o Repositório</a>
                </div>                   
                </div>
            </div>
        </div>
        
    </section>

<footer>
<span>Criado por <a href="https://augustodomingos.netlify.app/">Augusto Domingos</a> | <span class="far fa-copyright"></span> 2023 Todos os direitos reservados.</span>
</footer>
    <script src="{% static 'script.js' %}"></script>
</body>

formulario/templates/projetos-html-css-javascript.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projetos Páginas Web | Augusto Domingos</title>
    <link rel="icon" href="{% static 'images/icon/GD_ICON_TELA.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
    <script src="{% static 'js/all.min.6.1.1.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/typed.min.js' %}"></script>
   
</head>
<body>
    <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="{% url 'formulario:enviar_mensagem' %}">Proje<span>tos</span></a> </div>
            <ul class="menu">
                <li><a href="index.html#home">Início</a></li>
                <li><a href="index.html#about">Sobre</a></li>
                <li><a href="index.html#services">Projetos</a></li>
                <li><a href="index.html#skills">Skills</a></li>
                <li><a href="index.html#contact">Contacto</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>

    <!-- seção da página inicial -->
    <section class="about" id="about">
        <div class="max-width">
            <h2 class="title">Formulário de Login Responsivo - HTML, CSS e JavaScript</h2>
                
            <div class="about-content">
                <div class="column left">
                    <img src="{% static 'images/projetos/projetoweb_001.png' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p class="p1">Uma página de formulário de login simples e responsiva, desenvolvida usando o HTML, CSS e Javascript. Abaixo eu deixei o repositório
                        do Github e a página web online para uma demonstração rápida!</p>
        
                    <h2 class="text2">Demonstração da Página</h2>
                    <p class="p1"><a class='a1' href="https://aghastygd.github.io/formulario-de-login/" target = "_blank"> Abrir a Página Web</a>
                </div>                   
                </div>
            </div>
        </div>
        
    </section>

<footer>
<span>Criado por <a href="https://augustodomingos.netlify.app/">Augusto Domingos</a> | <span class="far fa-copyright"></span> 2023 Todos os direitos reservados.</span>
</footer>
    <script src="{% static 'script.js' %}"></script>
</body>

formulario/templates/projetos-python.html
{% load static %}

<!DOCTYPE html>
<html lang="PT-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Projetos Python | Augusto Domingos</title>
    <link rel="icon" href="{% static 'images/icon/GD_ICON_TELA.ico' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sobre.css' %}">
    <script src="{% static 'js/all.min.6.1.1.js' %}"></script>
    <script src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
    <script src="{% static 'js/typed.min.js' %}"></script>
   
</head>
<body>
    <div class="scroll-up-btn">
        <i class="fas fa-angle-up"></i>
    </div>
    <nav class="navbar">
        <div class="max-width">
            <div class="logo"><a href="{% url 'formulario:enviar_mensagem' %}">Proje<span>tos</span></a> </div>
            <ul class="menu">
                <li><a href="index.html#home">Início</a></li>
                <li><a href="index.html#about">Sobre</a></li>
                <li><a href="index.html#services">Projetos</a></li>
                <li><a href="index.html#skills">Skills</a></li>
                <li><a href="index.html#contact">Contacto</a></li>
            </ul>
            <div class="menu-btn">
                <i class="fas fa-bars"></i>
            </div>
        </div>
    </nav>

    <!-- seção da página inicial -->
    <section class="about" id="about">
        <div class="max-width">
            <h2 class="title">Sistema de CRUD - Tkinter + SQLite</h2>
                
            <div class="about-content">
                <div class="column left">
                    <img src="{% static 'images/projetos/projetopy_001.PNG' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p>Um sistema para gestão de clientes, funcionários, ou estudantes com uma interface super amigável. Usando o Python com a biblioteca SQLite para banco de dados e Tkinter como interface gráfica.</p>
                    <h2 class="text2">Funcionamento do Sistema</h2>
                    <p>Facilite o cadastro e gerenciamento de usuários, este sistema tem a possiblidade de adicionar, atualizar, consultar e remover dados. Os usuários cadastrados, poderão fazer o login em sua conta e acessar algumas ferramentas úteis para
                        o seu dia-a-dia de trabalho. Desenvolvi um menu de opções para facilitar a escolha dos serviços disponíveis. Entre os serviços estão: Cálculo de Média, Medidor, Jogo da Velha, Tabuada e muitas outras opcões que vale muito apena conferir.         
                    </p>
                    <h2 class="text2">Demonstração do Sistema</h2>
                    <p><a href="https://github.com/AghastyGD/Sistema-de-CRUD-Tkinter-SQLite" target = "_blank" >Abrir o Repositório</a>
                </div>                   
                </div>
            </div>
        </div>
        
    </section>
    
    <section class="about2" id="about2">
        <div class="max-width">
            <h2 class="title">Tic Tac Toe (Jogo da Velha) - Tkinter + Numpy</h2>
                
            <div class="about2-content2">
                <div class="column left">
                    <img src="{% static 'images/projetos/projetopy_002.PNG' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p class="p1">Este é um Jogo da Velha feito em Python para você jogar com o seu amigo. Desenvolvi utilizando o Tkinter Bootstrap como Interface Gráfica e Numpy para a lógica do jogo.</p>
                    <h2 class="text2">Jogabilidade</h2>
                    <p class="p1">Modo de Jogo: Player 1 vs Player 2</p>

                    <p class="p1"> Controles: Botão Direito do Mouse</p>
                        
                    <p class="p1">Regras do Jogos: É um jogo de regras extremamente simples, que não traz grandes dificuldades para seus jogadores e é facilmente aprendido.
                    </p>
                    <h2 class="text2">Demonstração do Jogo</h2>
                    <p class="p1"> <a class="a1" href="https://github.com/AghastyGD/Tic-Tac-Toe-Jogo-da-Velha-GUI-Tkinter" target="_blank" >Abrir o Repositório</a>
                </div>                 
                </div>
            </div>
        </div>
        
    </section>
    
    <section class="about3" id="about3">
        <div class="max-width">
            <h2 class="title">GDPlayer (Reprodutor de Música) - Tkinter + PyGame</h2>
                
            <div class="about3-content3">
                <div class="column left">
                    <img src="{% static 'images/projetos/projetopy_003.PNG' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p class="p1">Um Reprodutor de Músicas simples usando o Python e com uma interface super amigável para trazer boa experiência ao usuário.</p>
                    <h2 class="text2">Demonstração do Reprodutor</h2>
                    <p class="p1"><a class="a1" href="https://github.com/AghastyGD/GDPlayer-Reprodutor-de-Musica-Tkinter" target = "_blank" >Abrir o Repositório</a>
                </div>                   
                </div>
            </div>
        </div>
        
    </section>

    <section class="about4" id="about4">
        <div class="max-width">
            <h2 class="title">App para Cotação de Moedas Cripto - Kivy</h2>
                
            <div class="about4-content4">
                <div class="column left">
                    <img src="{% static 'images/projetos/projetopy_004.PNG' %}" alt="">

                </div>
                <div class="column right">
                    <div class="text">Introdução</div>
                    <p class="p1"> Uma aplicação em Kivy que acessa o serviço fornecido por uma  API externa que fornece a cotação em dólar, de uma criptomoeda.
                        Utlizei a API fornecida pela coincap, por ela ser simples e não exigir chave para o acesso.  O aplicativo pode ser, posteriormente, instalado em um celular.
                        </p>
                    <h2 class="text2">Demonstração da Aplicação</h2>
                    <p class="p1"><a class="a1" href="https://github.com/AghastyGD/cotacao_de_cripto_moeda" target = "_blank" >Abrir o Repositório</a>
                </div>                   
                </div>
            </div>
        </div>
        
    </section>
    
</footer>
<footer>
<span>Criado por <a href="https://augustodomingos.netlify.app/">Augusto Domingos</a> | <span class="far fa-copyright"></span> 2023 Todos os direitos reservados.</span>
</footer>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>